export const PricingPlans = [
    {
        name: "Basic",
        title: "GET THE BASIC, FREE",
        price: 0,
        frequency: "/month",
        description: "For individuals that need to record & share quick videos.",
        features: ["Screen & cam recording", "Comments & reactions", "Viewer Insights"],
        cta: "Get Basic For Free",
        mostpopuler: false,
    },
    {
        name: "Business",
        title: "EVERTING IN PRO, PLUS",
        price: 15,
        frequency: "/month",
        description: "For individuals teams that need advanced sharing & reporting.",
        features: ["Team Video Library", "Custom Branding", "Engagement Insights"],
        cta: "Request Access",
        mostpopuler: true,
    },
    {
        name: "Pro",
        title: "EVERTING IN BASIC, PLUS",
        price: 5,
        frequency: "/month",
        description: "For individuals that need advanced recording & editing.",
        features: ["Drawing Tool", "Custom Recording & Dimension", "Calls-to-Action"],
        cta: "Start Free Trial",
        mostpopuler: false,
    },
];
